@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package thatmartinguy.thedarkness.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
