@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package thatmartinguy.thedarkness.event;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
